### ISSUE TITLE
Invalid SSL/TLS Certificate Configuration

### ISSUE THREAD

**Issue by JoshuaWebb** [tms/shouldiblamecaching.com#1]
Presumably some required step has changed since this was initially setup, possibly some form of caching error ;)

![2019-03-12 14_34_57-Privacy error](https://user-images.githubusercontent.com/6722399/54173009-400f2280-44d4-11e9-978e-6b927b5290d2.png)

**Comment by catb0t** [comment]
```shell
$ curl -I https://shouldiblamecaching.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'shouldiblamecaching.com'
```

**Comment by tms** [comment]
I meant to do this after GitHub Pages introduced support some time ago and totally forgot, so [a little wait later](https://twitter.com/tmslft/status/1157469410921189376) and this is finally taken care of: https://shouldiblamecaching.com/

Thanks!
